module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {},
  },
  daisyui: {
    themes: [
      {
        heitorado: {
          primary: "#20a31b",
          secondary: "#29d1a1",
          accent: "#ffc0a0",
          neutral: "#202732",
          "base-100": "#213445",
          info: "#869AF3",
          success: "#136C5F",
          warning: "#A05C0D",
          error: "#FC5F62",
          "--rounded-badge": "0.15rem",
          "--rounded-box": "0.2rem",
        },
      },
      "light",
      "dark",
      "cupcake",
      "bumblebee",
      "emerald",
      "corporate",
      "synthwave",
      "retro",
      "cyberpunk",
      "valentine",
      "halloween",
      "garden",
      "forest",
      "aqua",
      "lofi",
      "pastel",
      "fantasy",
      "wireframe",
      "black",
      "luxury",
      "dracula",
      "cmyk",
      "autumn",
      "business",
      "acid",
      "lemonade",
      "night",
      "coffee",
      "winter",
    ],
  },
  plugins: [require("daisyui")],
};
